name: General Request
description: Suggest anything
title: "[GENERAL] "
body:
- type: markdown
  attributes:
    value: |
      **Repository**
      Are you sure this is the correct repository? As for both sync and async versions, there are seperate repositories. If you want to request something that both versions have, visit the sync repository [issue](https://github.com/Arcader717/DisOAuth2/issues) page

      **Be clear**
      Try to be as clear, and to the point about the request

      **What do you want out of it?**
      Tell us what you want out this, after the request has been completed. An example being how the code operates, or when a release will approximately come out
- type: checkboxes
  id: repository-check
  attributes:
    label: Are you in the correct repository?
    options:
    - label: Yes
      required: true
- type: textarea
  attributes:
    label: Request
    description: You can use markdown
    render: Markdown
  validations:
    required: true
